Update detectsecret.yml

diff --git a/.github/workflows/detectsecret.yml b/.github/workflows/detectsecret.yml
--- a/.github/workflows/detectsecret.yml
+++ b/.github/workflows/detectsecret.yml
@@ -26,7 +26,7 @@ jobs:
 
       - name: Run detect-secrets
         run: |
-          detect-secrets --scan > secrets_report.txt || echo "Secret detection failed"
+          detect-secrets scan > secrets_report.txt || echo "Secret detection failed"
 
       - name: List files
         run: ls -la
