Update trivy-scan.yml

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -26,7 +26,10 @@ jobs:
 
       - name: Run Trivy SCA scan
         run: |
-          trivy fs --scanners vuln --severity HIGH,CRITICAL,MEDIUM,LOW --ignore-unfixed --format table .
+          trivy fs --scanners vuln --severity HIGH,CRITICAL,MEDIUM,LOW --ignore-unfixed --format table . > trivy_report.txt || echo "Trivy scan failed"
+
+      - name: List files
+        run: ls -la
 
       - name: Upload Trivy report
         if: always()
